### PR TITLE
Enforce order in sending messages by queueing data submission. Fixes #8

### LINKED ISSUE #8: Potentially sends messages out of order
Especially an issue when paired with hubot-chunkify.  

We should synchronously send messages using a message buffer and a callback on post

### PR DESCRIPTION
**Pull request by nsand**
POSTing to `@messageEndpoint` will drain messages from a queue only after the previous submission has completed. It is a bit slower when sending successive messages, but they do end up in the proper order.

### CODE REVIEW

**Comment by nsand** [comment]
@chen-ye This implementation is without adding a dependency on `async`. If you'd prefer--and don't mind the addition of a new dependency--I could use `async.queue`.

**Comment by chen-ye** [comment]
Hi!  Sorry for the delay, taking a look now!

**Comment by nsand** [comment]
No worries. Much appreciated!

**Comment by nsand** [comment]
Hi, @chen-ye . Have you had a chance to look at merging this PR?

**Comment by clanzen** [comment]
+1 I'd like to see this PR merged as well.

**Comment by chen-ye** [comment]
merging! sorry for the wait; i was actually @ fb this summer

**Comment by nsand** [comment]
No worries, thanks for merging this, @chen-ye ! Hopefully you enjoyed your time at fb.

**Pull request merged**
